// Generated by CoffeeScript 1.6.3
(function() {
  var avatars, xhr;

  if (!String.prototype.trim) {
    String.prototype.trim = function() {
      return this.replace(/^\s+|\s+$/g, "");
    };
  }

  avatars = {};

  document.addEventListener("DOMNodeInserted", function(e) {
    var avatar, date, first, img, img_container, line, message, nick, sender, text, time, type;
    line = e.target;
    type = line.getAttribute("_type");
    nick = line.getAttribute("nick");
    if (type !== "privmsg" && type !== "notice") {
      return;
    }
    sender = line.querySelector(".sender");
    first = false;
    if (sender) {
      first = (sender.getAttribute("first")) === "true";
    }
    nick = nick.replace(/[0-9_]+$/, "");
    if (nick in avatars) {
      avatar = avatars[nick];
    } else if (nick === "***") {
      avatar = "http://res.cloudinary.com/riaf/image/upload/v1360133596/noimage.png";
    } else if (nick) {
      avatar = "http://res.cloudinary.com/riaf/image/facebook/w_25,h_25,c_thumb,g_face,d_contacts_kxvdl7.png/" + nick + ".png";
    } else {
      avatar = "http://res.cloudinary.com/riaf/image/upload/v1360133596/noimage.png";
    }
    img_container = document.createElement("span");
    img_container.setAttribute("class", "midtown-avatar");
    img_container.setAttribute("first", first ? "true" : "false");
    img = document.createElement("img");
    img.src = avatar;
    img_container.appendChild(img);
    line.insertBefore(img_container, line.firstChild);
    message = line.querySelector(".message");
    text = message.textContent.trim();
    date = text.replace(/^\[([0-9\/: ]+?)\] .+$/, "$1");
    if (date.match(/^[0-9\/: ]+$/)) {
      time = line.querySelector(".time");
      time.textContent = date;
      return message.innerHTML = message.innerHTML.replace("[" + date + "]", "");
    }
  });

  xhr = new XMLHttpRequest;

  xhr.open("GET", "https://raw.github.com/riaf/limechat-theme-midtown/master/avatars.json");

  xhr.onreadystatechange = function() {
    var data, item, _i, _len, _ref;
    if (xhr.readyState === 4 && xhr.status === 200) {
      data = JSON.parse(xhr.responseText);
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        item = data[_i];
        if (((_ref = item.data) != null ? _ref.nick : void 0) != null) {
          avatars[item.data.nick] = item.data.image;
        }
      }
    }
    return true;
  };

  xhr.send();

}).call(this);