// Generated by CoffeeScript 1.6.3
(function() {
  var avatars, xhr;

  avatars = {};

  document.addEventListener("DOMNodeInserted", function(e) {
    var avatar, first, img, img_container, line, nick, sender, type;
    line = e.target;
    type = line.getAttribute("type");
    nick = line.getAttribute("nick");
    if (type !== "privmsg" && type !== "notice") {
      return;
    }
    sender = line.querySelector(".sender");
    first = false;
    if (sender) {
      first = (sender.getAttribute("first")) === "true";
    }
    nick = nick.replace(/_+$/, "");
    if (nick in avatars) {
      avatar = avatars[nick];
    } else if (nick === "***") {
      avatar = "http://res.cloudinary.com/riaf/image/upload/v1360133596/noimage.png";
    } else if (nick) {
      avatar = "http://res.cloudinary.com/riaf/image/facebook/w_25,h_25,c_thumb,g_face/" + nick + ".png";
    } else {
      avatar = "http://res.cloudinary.com/riaf/image/upload/v1360133596/noimage.png";
    }
    img_container = document.createElement("span");
    img_container.setAttribute("class", "midtown-avatar");
    img_container.setAttribute("first", first ? "true" : "false");
    img = document.createElement("img");
    img.src = avatar;
    img_container.appendChild(img);
    return line.insertBefore(img_container, line.firstChild);
  });

  xhr = new XMLHttpRequest;

  xhr.open("GET", "http://wedata.net/databases/limechat-theme-midtown-avatars/items.json");

  xhr.onreadystatechange = function() {
    var data, item, _i, _len, _ref;
    if (xhr.readyState === 4 && xhr.status === 200) {
      data = JSON.parse(xhr.responseText);
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        item = data[_i];
        if (((_ref = item.data) != null ? _ref.nick : void 0) != null) {
          avatars[item.data.nick] = item.data.image;
        }
      }
    }
    return true;
  };

  xhr.send();

}).call(this);