// Generated by CoffeeScript 1.4.0
(function() {
  var avatars, xhr;

  avatars = {};

  document.addEventListener("DOMNodeInserted", function(e) {
    var avatar, first, img, img_container, line, nick, sender, type;
    line = e.target;
    type = line.getAttribute("type");
    nick = line.getAttribute("nick");
    if (type !== "privmsg" && type !== "notice") {
      return;
    }
    sender = line.querySelector(".sender");
    first = false;
    if (sender) {
      first = (sender.getAttribute("first")) === "true";
    }
    nick = nick.replace(/_+$/, "");
    if (nick in avatars) {
      nick = avatars[nick];
    }
    if (nick) {
      avatar = "http://res.cloudinary.com/riaf/image/facebook/w_25,h_25,c_fill/" + nick + ".png";
    } else {
      avatar = "http://res.cloudinary.com/riaf/image/upload/v1360133596/noimage.png";
    }
    img_container = document.createElement("span");
    img_container.setAttribute("class", "midtown-avatar");
    img_container.setAttribute("first", first ? "true" : "false");
    img = document.createElement("img");
    img.src = avatar;
    img_container.appendChild(img);
    return line.insertBefore(img_container, line.firstChild);
  });

  xhr = new XMLHttpRequest;

  xhr.open("GET", "https://raw.github.com/riaf/limechat-theme-midtown/master/avatars.json");

  xhr.onreadystatechange = function() {
    if (xhr.readyState === 4 && xhr.status === 200) {
      return avatars = JSON.parse(xhr.responseText);
    }
  };

  xhr.send();

}).call(this);